src/MyStock/ViewModels/ProviderViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MyStock.ViewModels
{
    public class ProviderViewModel
    {
        [Key]
        public Guid Id { get; set; }

        [Display(Name = "Nome")]
        [Required(ErrorMessage = "o campo é obrigatório")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "o campo precisa ter entre {2} e {1} caracteres")]
        public string Name { get; set; }

        [Display(Name = "CPF/CNPJ")]
        [Required(ErrorMessage = "o campo é obrigatório")]
        public string DocumentNumber { get; set; }

        [Display(Name = "Tipo")]
        public int ProviderType { get; set; }

        [Display(Name = "Ativo?")]
        public bool Active { get; set; }
        public AddressViewModel Address { get; set; }
        public List<ProductViewModel> Products { get; set; }
    }
}

src/MyStock/Controllers/ProvidersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyStock.Business.Interfaces;
using MyStock.Business.Interfaces.Repository;
using MyStock.Business.Interfaces.Services;
using MyStock.Business.Models;
using MyStock.Data.Exceptions;
using MyStock.Extensions.Authentication;
using MyStock.ViewModels;

namespace MyStock.Controllers
{
    [Authorize]
    [Route("Fornecedores")]
    public class ProvidersController : BaseController
    {
        private readonly IProviderRepository _providerRepository;
        private readonly IProviderService _providerService;
        private readonly IMapper _mapper;

        public ProvidersController(IProviderRepository providerRepository, IProviderService providerService, IMapper mapper, INotifier notifier) : base(notifier)
        {
            _providerRepository = providerRepository;
            _providerService = providerService;
            _mapper = mapper;
        }

        [AllowAnonymous]
        [Route("Index")]
        public async Task<IActionResult> Index()
        {
            var providers = _mapper.Map<List<ProviderViewModel>>(await _providerRepository.FindAll(true));
            return View(providers.OrderBy(x => x.Name));
        }

        [AllowAnonymous]
        [Route("Detalhes/{id:guid}")]
        public async Task<IActionResult> Details(Guid id)
        {
            var provider = await GetById(id, true, false);

            if (provider == null) return NotFound();

            return View(provider);
        }

        [ClaimsAuthorize("Provider", "Add")]
        [Route("Novo")]
        public IActionResult Create()
        {
            return View();
        }

        [ClaimsAuthorize("Provider", "Add")]
        [Route("Novo")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProviderViewModel obj)
        {
            obj.DocumentNumber = obj.DocumentNumber.Replace(".", "").Replace("-", "").Replace("/", "");

            var provider = _mapper.Map<Provider>(obj);
            await _providerService.Insert(provider);
            if (!ValidOperation()) return View(obj);

            TempData["Success"] = "Fornecedor cadastrado com sucesso.";
            return RedirectToAction(nameof(Index));
        }

        [ClaimsAuthorize("Provider", "Edit")]
        [Route("Editar/{id:guid}")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var providerViewModel = await GetById(id, true, true);

            if (providerViewModel == null) return NotFound();

            return View(providerViewModel);
        }

        [ClaimsAuthorize("Provider", "Edit")]
        [Route("Editar/{id:guid}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, ProviderViewModel obj)
        {
            if (id != obj.Id) return NotFound();

            if (!ModelState.IsValid) return View(obj);

            obj.DocumentNumber = obj.DocumentNumber.Replace(".", "").Replace("-", "").Replace("/", "");

            var provider = _mapper.Map<Provider>(obj);
            await _providerService.Update(provider);
            if (!ValidOperation()) return View(obj);

            TempData["Success"] = "Fornecedor atualizado com sucesso.";
            return RedirectToAction(nameof(Index));

        }

        [ClaimsAuthorize("Provider", "Del")]
        [Route("Excluir/{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var providerViewModel = await GetById(id, false, false);

            if (providerViewModel == null) return NotFound();

            return View(providerViewModel);
        }

        [ClaimsAuthorize("Provider", "Del")]
        [Route("Excluir/{id:guid}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            try
            {
                var providerViewModel = await GetById(id, true, false);

                if (providerViewModel == null) return NotFound();

                await _providerService.Remove(id);
                if (!ValidOperation()) return View(providerViewModel);

                TempData["Success"] = "Fornecedor excluído com sucesso.";

                return RedirectToAction(nameof(Index));
            }
            catch(IntegrityException ex)
            {
                var providers = _mapper.Map<List<ProviderViewModel>>(await _providerRepository.FindAll(true));
                ViewData.ModelState.AddModelError(string.Empty, $"{ex.Message} existem produtos pertencentes a este fornecedor.");
                return View("Index", providers.OrderBy(p => p.Name));
            }
        }

        [ClaimsAuthorize("Provider", "EditAddress")]
        [Route("Editar-endereco/{providerId:guid}")]
        public async Task<IActionResult> EditAddress(Guid providerId)
        {
            var provider = await GetById(providerId, true, false);
            if (provider == null)
            {
                return NotFound();
            }

            return PartialView("_UpdateAddress", new ProviderViewModel { Address = provider.Address });
        }

        [ClaimsAuthorize("Provider", "EditAddress")]
        [Route("Editar-endereco/{providerId:guid}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAddress(ProviderViewModel viewModel)
        {
            ModelState.Remove("Name");
            ModelState.Remove("DocumentNumber");
            if (ModelState.IsValid)
            {
                await _providerService.UpdateAddress(_mapper.Map<Address>(viewModel.Address));
                if (!ValidOperation()) return PartialView("_UpdateAddress", viewModel);

                var url = Url.Action("GetAddress", "Providers", new { providerId = viewModel.Address.ProviderId });
                return Json(new { success = true, url });
            }

            return PartialView("_UpdateAddress", viewModel);
        }

        private async Task<ProviderViewModel> GetById(Guid id, bool address, bool products)
        {
            if (address)
            {
                if (products)
                    return _mapper.Map<ProviderViewModel>(await _providerRepository.FindById(id, true, true));
                return _mapper.Map<ProviderViewModel>(await _providerRepository.FindById(id, true, false));
            }
            return _mapper.Map<ProviderViewModel>(await _providerRepository.FindById(id));
        }
    }
}

src/MyStock/Extensions/SummaryErrorsViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyStock.Business.Interfaces;

namespace MyStock.Extensions
{
    public class SummaryErrorsViewComponent : ViewComponent
    {
        private readonly INotifier _notifier;

        public SummaryErrorsViewComponent(INotifier notifier)            
        {
            _notifier = notifier;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notifications = await Task.FromResult(_notifier.GetNotifications());       
            notifications.ForEach(x => ViewData.ModelState.AddModelError(string.Empty, x.Message));     
            return View();
        }
    }
}

src/MyStock/Views/Providers/Create.cshtml
@model ProviderViewModel

@{
    ViewData["Title"] = "Novo Fornecedor";
}

<h4>@ViewData["Title"]</h4>
<hr />
<vc:summary-errors></vc:summary-errors>
<div class="row">
    <div class="col-md-10">
        <form asp-action="Create">
            <div class="form-row">
                <div class="form-group col-md-8">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="DocumentNumber" class="control-label"></label>
                    <input asp-for="DocumentNumber" class="form-control" id="document"/>
                    <span asp-validation-for="DocumentNumber" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <div class="form-check form-check-inline">
                        <input asp-for="ProviderType" class="form-check-input" type="radio" name="providerType" id="inlineCheckbox1" value="1" checked onclick="formatar(1)">
                        <label class="form-check-label" for="inlineCheckbox1">Pessoa Física</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input asp-for="ProviderType" class="form-check-input" type="radio" name="providerType" id="inlineCheckbox2" value="2" onclick="formatar(2)">
                        <label class="form-check-label" for="inlineCheckbox2">Pessoa Jurídica</label>
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                        </label>
                    </div>
                </div>
            </div>
            <h4>Endereço</h4>
            <hr>
            <partial name="_Address">
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-info">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    <script>
        $("#document").mask("000.000.000-00")
        const formatar = (x) => {
            if (x === 2) {
                $("#document").mask("00.000.000/0000-00")
            } else {
                $("#document").mask("000.000.000-00")
            }
        }

        BuscaCep();
</script>
}

src/MyStock/Views/Providers/Delete.cshtml
@model ProviderViewModel

@{
    ViewData["Title"] = "Excluir Fornecedor";
}

<h3>Confirmar exclusão do fornecedor?</h3>
<vc:summary-errors></vc:summary-errors>
<div>
    <h4>@Model.Name</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DocumentNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DocumentNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-info">Voltar</a>
    </form>
</div>

src/MyStock/Views/Providers/Details.cshtml
@model ProviderViewModel

@{
    ViewData["Title"] = @Model.Name;
}

<div>
    <h4>@Model.Name</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DocumentNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DocumentNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Editar</a>
    <a asp-action="Index" class="btn btn-info">Voltar</a>
</div>
<partial name="_AddressDetails"></partial>

src/MyStock/Views/Providers/Edit.cshtml
@model ProviderViewModel

@{
    ViewData["Title"] = "Editar Fornecedor";
}

<h4>@ViewData["Title"]</h4>
<hr />
<form asp-action="Edit">
    <div class="row">
        <div class="col-md-4">
            <vc:summary-errors></vc:summary-errors>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocumentNumber" class="control-label"></label>
                <input asp-for="DocumentNumber" class="form-control" id="document" />
                <span asp-validation-for="DocumentNumber" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-info">Voltar</a>
            </div>
        </div>
        <div class="col-md-4">
            <br>
            <div class="form-group">
                <div class="form-check form-check-inline">
                    <input asp-for="ProviderType" class="form-check-input" type="radio" name="providerType" id="inlineCheckbox1" value="1" onclick="formatar(1)">
                    <label class="form-check-label" for="inlineCheckbox1">Pessoa Física</label>
                </div>
                <div class="form-check form-check-inline">
                    <input asp-for="ProviderType" class="form-check-input" type="radio" name="providerType" id="inlineCheckbox2" value="2" onclick="formatar(2)">
                    <label class="form-check-label" for="inlineCheckbox2">Pessoa Jurídica</label>
                </div>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
        </div>
    </div>
</form>

<div id="AddressTarget">
    <partial name="_AddressDetails">
</div>

<div>
    <br>
    <h4>Produtos</h4>
    <hr />
    <partial name="_ProductsList" model="@Model.Products">
</div>

<div id="myModal" class="modal fade in">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id="myModalContent"></div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    <script>
        $(document).ready(function () {
            if ($('#inlineCheckbox2').prop('checked')) {
                $("#document").mask("00.000.000/0000-00")
            } else {
                $("#document").mask("000.000.000-00")
            }
            AjaxModal();
        });
        const formatar = (x) => {
            if (x === 2) {
                $("#document").val('')
                $("#document").mask("00.000.000/0000-00")
            } else {
                $("#document").val('')
                $("#document").mask("000.000.000-00")
            }
        }
    </script>
}

src/MyStock/Views/Providers/Index.cshtml
@model IEnumerable<ProviderViewModel>

@{
    ViewData["Title"] = "Fornecedores";
}

<h1>@ViewData["Title"]</h1>
<hr>
<vc:summary-errors></vc:summary-errors>
<a asp-action="Create" disable-by-claim-name="Provider" disable-by-claim-value="Add" data-toggle="tooltip" data-placement="right" class="btn btn-primary">Novo Fornecedor</a>
<p></p>
<table class="table table-hover table-responsive-md">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.DocumentNumber)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Address.Street)
            </th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td class="document-number">
                @Html.DisplayFor(modelItem => item.DocumentNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address.Street)
            </td>
            <td class="text-right">
                <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id" data-toggle="tooltip" data-placement="top"><i class="fas fa-info-circle"></i></a>
                <a class="btn btn-warning" asp-action="Edit" disable-by-claim-name="Provider" disable-by-claim-value="Edit" asp-route-id="@item.Id" data-toggle="tooltip" data-placement="top" title="editar fornecedor"><i class="fas fa-edit"></i></a>
                <a class="btn btn-danger" asp-action="Delete" disable-by-claim-name="Provider" disable-by-claim-value="Del" asp-route-id="@item.Id"><i class="fas fa-trash-alt" data-toggle="tooltip" data-placement="top" title="excluir fornecedor"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    <script>
        $(document).ready( function() {
            $('.document-number').each(function() {
                console.log($(this).text().trim().length)
                if ($(this).text().trim().length == 11) {
                    $(this).mask("000.000.000-00")
                } else {
                    $(this).mask("00.000.000/0000-00")
                }
            })
            }
        )
</script>
}

src/MyStock/Views/Providers/_Address.cshtml
@model ProviderViewModel

<div class="form-row">
    <div class="form-group col-md-2">
        <label asp-for="Address.Cep" class="control-label"></label>
        <input asp-for="Address.Cep" class="form-control" />
        <span asp-validation-for="Address.Cep" class="text-danger"></span>
    </div>
    <div class="form-group col-md-8">
        <label asp-for="Address.Street" class="control-label"></label>
        <input asp-for="Address.Street" class="form-control" />
        <span asp-validation-for="Address.Street" class="text-danger"></span>
    </div>
    <div class="form-group col-md-2">
        <label asp-for="Address.Number" class="control-label"></label>
        <input asp-for="Address.Number" class="form-control">
        <span asp-validation-for="Address.Number" class="text-danger"></span>
    </div>
</div>
<div class="form-row">
    <div class="form-group col-md-6">
        <label asp-for="Address.Complement" class="control-label"></label>
        <input asp-for="Address.Complement" class="form-control">
        <span asp-validation-for="Address.Complement" class="text-danger"></span>
    </div>
    <div class="form-group col-md-6">
        <label asp-for="Address.District" class="control-label"></label>
        <input asp-for="Address.District" class="form-control">
        <span asp-validation-for="Address.District" class="text-danger"></span>
    </div>
</div>
<div class="form-row">
    <div class="form-group col-md-8">
        <label asp-for="Address.City" class="control-label"></label>
        <input asp-for="Address.City" class="form-control">
        <span asp-validation-for="Address.City" class="text-danger"></span>
    </div>
    <div class="form-group col-md-4">
        <label asp-for="Address.State" class="control-label"></label>
        <input asp-for="Address.State" class="form-control">
        <span asp-validation-for="Address.State" class="text-danger"></span>
    </div>
</div>

src/MyStock/Views/Providers/_AddressDetails.cshtml
@model ProviderViewModel

<br>
<h4>Endereço</h4>
<hr />
@if (Model != null)
{
    <table class="table table-hover table-responsive-md">
        <thead class="thead-dark">
            <tr>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Address.Street)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Address.Number)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Address.Complement)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Address.District)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Address.Cep)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Address.City)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Address.State)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.Address.Street)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Address.Number)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Address.Complement)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Address.District)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Address.Cep)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Address.City)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Address.State)
                </td>
                <td>
                    <a asp-action="EditAddress" data-modal="" asp-route-providerId="@Model.Id" class="btn btn-info" disable-by-claim-name="Provider" disable-by-claim-value="EditAddress" data-toggle="tooltip" data-placement="top" title="editar endereço" supress-by-action="Details"><i class="fas fa-pencil-alt"></i></a>
                </td>
            </tr>
        </tbody>
    </table>
}

src/MyStock/Views/Providers/_UpdateAddress.cshtml
@model ProviderViewModel

@{
    ViewData["Title"] = "Atualizar Endereço";
}

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Atualizar Endereço</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form asp-action="EditAddress">
    <div class="modal-body">
        <input type="hidden" asp-for="Address.ProviderId">
        <input type="hidden" asp-for="Address.Id">
        <partial name="_Address">
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </div>
</form>

<script>
    BuscaCep();
</script>